Repository Flying-Free/pyopenproject, pull requests merged in 2021-03, with the labels that each got.

#9 Include dependences in setup.py
  .env
  Makefile
  setup.py
Labels: enhancement

#11 Changes in setup.py
  CHANGELOG.md
  setup.py
Labels: bug

#13 v0.4
  .env
  CHANGELOG.md
  Makefile
  pyopenproject/business/services/command/user/find_by_context.py
  pyopenproject/business/services/user_service_impl.py
  pyopenproject/business/user_service.py
  tests/test_cases/user_service_test.py
Labels: enhancement

#14 New Release v0.5
  .env
  CHANGELOG.md
  pyopenproject/business/project_service.py
  pyopenproject/business/services/command/project/find_by_context.py
  pyopenproject/business/services/project_service_impl.py
  tests/test_cases/role_service_test.py
Labels: bug, enhancement

#18 New release v0.7
  .env
  CHANGELOG.md
  pyopenproject/business/services/command/user/invite.py
  pyopenproject/business/services/user_service_impl.py
  pyopenproject/business/user_service.py
Labels: enhancement

#22 New release v0.7.2
  .env
  CHANGELOG.md
  __init__.py
Labels: bug

#25 Dev v0.7.4
  .env
  CHANGELOG.md
  pyopenproject/business/priority_service.py
  pyopenproject/business/services/command/time_entry/find_between_days.py
  pyopenproject/business/services/command/user/create.py
  pyopenproject/business/services/command/user/invite.py
  pyopenproject/business/services/user_service_impl.py
  pyopenproject/business/user_service.py
  tests/test_cases/role_service_test.py
  tests/test_cases/time_entry_service_test.py
Labels: bug
